### ISSUE TITLE
HTML entities in text nodes returned as real HTML

### ISSUE THREAD

**Issue by ssorallen** [reactjs/react-magic#11]
When a TextNode is encountered, HTML entities inside it are returned as HTML rather than the HTML entity. This is problematic for the use of `&lt;` and `&gt;` in particular because the tags they wrap are then interpreted as real tags.

For example:

```
> converter.convert("<code>&lt;body&gt;</code>");
"<code><body></code>
"
```

The encoded symbols are returned as the symbols themselves, which eventually throws an error in Esprima because it encounters an unclosed tag.

This is expected and documented behavior of TextNodes and their `data` attribute, and it seems the way to get around it is to escape the characters differently before inserting the content into a real DOM node.

**Comment by ssorallen** [comment]
Related StackOverflow answers that explains why this happens: [text nodeValue containing HTML entity](http://stackoverflow.com/a/17583527/368697)

**Comment by ssorallen** [comment]
The simplest approach might be to escape ampersands in text passed to the converter:

```
> converter.convert("<code>&amp;gt;body&amp;lt;</code>")
"<code>&gt;body&lt;</code>
"
```

**Comment by Daniel15** [comment]
I used *one weird trick* to escape required symbols:
```javascript
var tempEl = document.createElement('div');
function escapeSpecialChars(value) {
  // Uses this One Weird Trick to escape text - Raw text inserted as textContent
  // will have its escaped version in innerHTML.
  tempEl.textContent = value;
  return tempEl.innerHTML;
}

escapeSpecialCharacters('<'); // &lt;
```

Although I just realised this won't work exactly right in Node.js where I use JSDom, so I'll have to move stuff around a bit.

**Comment by ssorallen** [comment]
The fix works great in browser.

Are the past couple fixes worthy of a minor version release or a patch release?

**Comment by Daniel15** [comment]
Yeah I think I'll do a patch release, just want to wait a few days and see
if any other small bug fixes come up.

--
Regards,
Daniel Lo Nigro
http://dan.cx/ | Twitter <http://twitter.com/Daniel15> | Facebook
<http://www.facebook.com/daaniel>
