### ISSUE TITLE
Fields with "value" attributes become uneditable after transform

### ISSUE THREAD

**Issue by ssorallen** [reactjs/react-magic#14]
In order for "value" to behave as it does in HTML, the created React components must use "defaultValue". "value" in React creates a [controlled component](https://facebook.github.io/react/docs/forms.html#controlled-components), which makes react-magic generate un-editable inputs.

Currently:

```
> converter.convert('<input value="Darth Vader">')
"<input value="Darth Vader" />
"
```

To behave as expected:

```
> converter.convert('<input value="Darth Vader">')
"<input defaultValue="Darth Vader" />
"
```

**Comment by ssorallen** [comment]
The same goes for `type="checkbox"` with the `checked` attribute. It should be converted to `defaultChecked`.

**Comment by aboobakkar** [comment]
the above same issue for me.. and i also checked article https://themeteorchef.com/tutorials/click-to-edit-fields-in-react and deafultValue is not worked thsi,state.something value

**Comment by aayushis12** [comment]
The same issue is with me. My Codepen link is https://codepen.io/asinha/pen/EXaZJm?editors=1111 , when I set getInitialValue to '' the input box becomes non-editable

**Comment by luanlucho** [comment]
Same issue!

**Comment by satishchadokar** [comment]
Same issue for input

**Comment by Virksaabnavjot** [comment]
same
