### ISSUE TITLE
HTML to JSX is broken

### ISSUE THREAD

**Issue by dhawkmoon** [reactjs/react-magic#143]
http://magic.reactjs.net/htmltojsx.htm 

is broken http://prntscr.com/gt7173

**Comment by cherhan** [comment]
Please help!

**Comment by flyg101** [comment]
I've been searching online and still cannot find the new location of the missing files... Maybe you could search too... The missing files are:
`live_editor.js, react.css, syntax.css`

**Comment by juan0087** [comment]
same here! Been trying to use the site for the past few days but it is still broken.

Hopefully it'll get fixed soon!

**Comment by Daniel15** [comment]
Should be OK now.
