### ISSUE TITLE
controlled components made uncontrolled

### ISSUE THREAD

**Issue by hallgren** [reactjs/react-magic#16]
Is there any way that a controlled component can be updated or made uncontrolled?

For example the ```<input type="submit" value="Send"/>``` will not update its value on a new value on render.

**Comment by ssorallen** [comment]
I changed that in a pull request that was merged to master, but the commits have not yet been included in a release: https://github.com/reactjs/react-magic/pull/15

The PR also changed `checked` to `defaultChecked` for the same reason you mentioned.

**Comment by Daniel15** [comment]
Are you using react-magic or HTMLtoJSX? 

Thanks for the reminder @ssorallen, I'll cut a release shortly. I was going to bundle some other bug fixes but I can do those separately.

**Comment by Daniel15** [comment]
Just pushed out an update to HTMLtoJSX. As for react-magic, it should already be up to date.

**Comment by ssorallen** [comment]
@Daniel15, where does HTMLtoJSX live? I thought it was part of react-magic.

**Comment by Daniel15** [comment]
HTMLtoJSX is the package on NPM, and is one portion of react-magic. It handles converting HTML to JSX, that's it.

React-magic is HTMLtoJSX + automatically converting the whole page to a React component + handling AJAX loading page transitions (ie. clicking URLs). React-magic is more experimental :P

The readme in this repo explains what react-magic is, whereas `README-htmltojsx.md` (and the readme on NPM) explain HTMLtoJSX.

**Comment by Daniel15** [comment]
In short, this is react-magic: https://github.com/reactjs/react-magic/blob/master/src/magic.js

**Comment by ssorallen** [comment]
Cool, thanks for the explanation. I see the new 0.2.1 package on NPM.

**Comment by hallgren** [comment]
defaultValue will not work on all types including type="submit" according to the react team it´s a button and not editable by a user. ref: https://github.com/facebook/react/issues/2673#issuecomment-65946425

Is it possible to work around this in HTMLtoJSX? I think and I have the issue that a submit button value can change between two diffing HTML elements.

**Comment by ssorallen** [comment]
Good point on the value of a `<input type="submit">`. It seems to work fine setting `defaultValue` though, even if it's not semantically meaningful.

**Comment by Daniel15** [comment]
If setting `defaultValue` rather than `value` on buttons doesn't work properly, I'd suggest opening a separate issue for it. Thanks!

**Comment by ssorallen** [comment]
@hallgren Aha, I see what you mean by the problem now. First page has an `<input type="submit" value="Submit">` and the second one has `<input type="submit" value="Click Me">`, and the value would not be reflected in the rendered DOM because HTMLtoJSX is setting `defaultValue` instead of `value`.

**Comment by hallgren** [comment]
I don´t know if it´s possible to update the value on the submit button due to how react.js handles the ```<input type="submit">``` button component. 

It work for the ```<button type="submit">text</button>``` tag.
