### ISSUE TITLE
HTML -> JSX parser barfs on <script> code

### ISSUE THREAD

**Issue by KyleAMathews** [reactjs/react-magic#2]
Error:

`Uncaught Error: Something bad happened when transforming HTML to JSX: Error: Parse Error: Line 31: Unexpected token var`

**Comment by Daniel15** [comment]
Closing this out, I think the issue with script tags was resolved.

**Comment by santagada** [comment]
it appears that now it is barfing on comments... like:



will open another ticket

**Comment by trusktr** [comment]
React is barfing on this:

```html
                <script id="shader-fs" type="x-shader/x-fragment">
                    precision mediump float;

                    void main(void) {
                        gl_FragColor = vec4(1.0, 1.0, 1.0, 1.0);
                    }
                </script>
```
