### ISSUE TITLE
Uncaught Error: Something bad happened when transforming HTML to JSX: TypeError: undefined is not a function

### ISSUE THREAD

**Issue by max107** [reactjs/react-magic#23]
in demo page

**Comment by inooid** [comment]
+1

**Comment by dongyuwei** [comment]
+1

**Comment by Daniel15** [comment]
Sorry for the delay, I didn't see this issue. This was due to the React version being too old. Fixed in dd091af8d61de3b2b80d833f9b3083cc32c751bd
