### ISSUE TITLE
HTMLtoJSX converter does not convert <textarea> and <pre> content correctly

### ISSUE THREAD

**Issue by sickslives** [reactjs/react-magic#33]
[Here's a fiddle](https://jsfiddle.net/jyth3h65/3/)

When HTML containing textarea's or pre's with newlines are fed into the [HTML to JSX converter](https://facebook.github.io/react/html-jsx.html), the newlines in the textarea or pre are not converted the way they need to be for multiline content to remain intact. See [why textarea value](https://facebook.github.io/react/docs/forms.html#why-textarea-value)

 [JSX whitespace coalescing rules](/facebook/react/pull/480) end up being applied when the result is rendered.

**Comment by Daniel15** [comment]
Fantastic bug report, thank you! I'll take a look.

**Comment by Daniel15** [comment]
Done in 9056a2755abe322f510deb8db3c517909fb9d53b, let me know if I missed any edge cases :)

**Comment by sickslives** [comment]
Thanks! One thing: textarea should use defaultValue instead of value, otherwise you can't edit the contents after they've been rendered.
