### ISSUE TITLE
/src/magic.js is not the same as reactjs.github.io/react-magic/magic.min.js

### ISSUE THREAD

**Issue by MikeWillis** [reactjs/react-magic#47]
I don't know if I'm missing something obvious, but I was looking for a non-minified version of magic.js and I noticed that this version:

- https://github.com/reactjs/react-magic/blob/master/src/magic.js

is not the same as this one (referenced in the usage instructions):

- http://reactjs.github.io/react-magic/magic.min.js

I'm new to github so maybe I'm missing something? It's not just that it's minified.

**Comment by Daniel15** [comment]
You can get a non-minified version at http://reactjs.github.io/react-magic/magic.js. The version in the repo (first link in your post) is the source version, whereas the version on the reactjs.github.io site is the compiled version that's been built using Webpack. Webpack pulls in all the libraries required by the `require` calls, for example.

You can find the contents of the site in the gh-pages branch: https://github.com/reactjs/react-magic/tree/gh-pages.

**Comment by MikeWillis** [comment]
I understand, thank you!!!!
