### ISSUE TITLE
Have website with HTML to JSX conversion here

### ISSUE THREAD

**Issue by zpao** [reactjs/react-magic#52]
I don't want https://facebook.github.io/react/html-jsx.html on our site anymore. It uses this project exclusively so this project should just host it's own site.

**Comment by Daniel15** [comment]
I can move it over, but why don't you want it on the React site any more?

**Comment by zpao** [comment]
It's not something we're spending any time thinking about or supporting so it feel disingenuous to have there in our official site.

**Comment by Daniel15** [comment]
Thanks, that makes sense. Can we redirect the old URL to the new one (once it's available)? I know Github Pages is super basic and doesn't allow proper 301 redirects, but we could at least have a meta redirect or something like that.

**Comment by zpao** [comment]
Yea, we'd definitely set up the redirect. I know the pains :) We have a few other pages that we're already redirecting

**Comment by Daniel15** [comment]
@zpao  - Sorry I haven't had a chance to do this yet, I'll follow up soon.

**Comment by Daniel15** [comment]
The new page is at http://magic.reactjs.net/htmltojsx.htm. Currently it hotlinks some files from the React site (stylesheet and live code editor) but I'm planning on making it properly standalone soon.

Submitted https://github.com/facebook/react/pull/6608 to update the React site to reflect this.

**Comment by trusktr** [comment]
Hey guys, maybe Facebook designers are all developers?

But for HTML/CSS designers, having to open up React JSX files and wade through JavaScript just to work on design is a bit impeding.

See https://github.com/reactjs/react-magic/issues/137 for examples on why things like Angular and Vue make designer lives easier, and by inference this tool could be used in a similar way to effectively add an HTML(with logic)-to-JSX conversion so designers can design and developers can develop, both sides collaborating, in a scalable way.

How does Facebook currently mitigate this problem? Or are designers at Facebook limited to graphical representations of their designs, after which developers must always update source code when graphical designs are changed?
