### ISSUE TITLE
Same functionality as the turbo-react library 

### ISSUE THREAD

**Issue by keyeh** [reactjs/react-magic#65]
Just a heads up for anyone wanting to have AJAX'd and diffed page loads in a more robust/mature library:

[Turbo React](https://github.com/ssorallen/turbo-react) is a drop-in library that does what react-magic does -- It loads new links via AJAX and uses React to diff the page, but without the complexity of HTMLtoJSX. It also works on any plain HTML site with no extra server configuration, and degrades gracefully on old browsers.

Demo here: https://turbo-react.herokuapp.com

It's built on the [Turbolinks library](https://github.com/turbolinks/turbolinks) from the Ruby on Rails community.

It also shares some of the same problems as react-magic, mainly breaking event bindings. Fortunately Turbolinks has it's own events for page changes/updates. Also, if you're using jQuery there is [a drop-in fix](https://github.com/kossnocorp/jquery.turbolinks/).

**Comment by ssorallen** [comment]
Turbo React author here.

Thanks for the mention. Turbo React actually uses react-magic (its NPM package is called ['htmltojsx'](https://www.npmjs.com/package/htmltojsx)) to convert from HTML to JSX and then uses React's JSXCompiler to go from JSX to React function calls. The more bugs that get addressed in react-magic, the better turbo-react can be at handling HTML.

A big benefit turbo-react would be for react-magic to output React function calls directly so the JSXCompiler is not needed (https://github.com/reactjs/react-magic/issues/19).
