### ISSUE TITLE
Website is not working

### ISSUE THREAD

**Issue by VanDavv** [reactjs/react-magic#89]
When i opened up http://magic.reactjs.net/htmltojsx.htm, page has frozen on loading screen.
![zrzut ekranu z 2016-11-22 08-57-55](https://cloud.githubusercontent.com/assets/5244214/20515477/2cec8450-b092-11e6-99a5-5a1f2bf6b647.png)

**Comment by Daniel15** [comment]
Strange, it works for me... What happens if you go to http://magic.reactjs.net/htmltojsx.min.js directly?

**Comment by VanDavv** [comment]
I can get the script correctly now. What's even more strange, now the site is not working at all for me (404 NotFound)

![zrzut ekranu z 2016-11-22 10-59-00](https://cloud.githubusercontent.com/assets/5244214/20519358/e7d64de0-b0a2-11e6-815d-0c3341ee78a9.png)

**Comment by VanDavv** [comment]
Everything is working now. Strange issue, I have no idea what as happened

**Comment by Daniel15** [comment]
Yeah I guess this was a GitHub Pages outage, as I saw the same thing for a different project (https://github.com/babun/babun.github.io/issues/13).
