### ISSUE TITLE
No releases in over a year?

### ISSUE THREAD

**Issue by ticky** [reactjs/react-magic#91]
The latest npm version of this is from October 2015, and there have been many fixes since (one in particular, #55, being one I want to rely on!)

It’d be great to get the latest published!

**Comment by Daniel15** [comment]
Oops, my mistake! I'll try to push a new release soon.

**Comment by ticky** [comment]
Thanks! :smile:

**Comment by Daniel15** [comment]
Published 0.2.6... Hopefully I did it right. Let me know if you see any problems.
